# This is an environment file for a traffic detection project using Streamlit and FastAPI.

name: dhaka-traffic-detection
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pip:
      - torch
      - streamlit
      - pillow
      - kaggle
      - opencv-python
      - python-multipart
      - fastapi
      - uvicorn
